# Generated by Django 5.2.dev20241016112319 on 2025-05-21 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_representation_alter_location_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Troupe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'troupes',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='troupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='artists', to='catalogue.troupe'),
        ),
    ]
